export const ACTIVITY_LOG_ACTIONS = [
  "USER_DEACTIVATED",
  "USER_ACTIVATED",
  "WALLET_BALANCE_UPDATED",
  "WALLET_MIN_TOPUP_UPDATED",
  "WALLET_TOPUP_APPROVED",
  "WALLET_TOPUP_REJECTED",
  "SUBSCRIPTION_CREATED",
  "SUBSCRIPTION_PAUSED",
  "SUBSCRIPTION_ACTIVATED",
  "AFFILIATE_CREATED",
  "AFFILIATE_COMISSION_ENABLED",
  "AFFILIATE_COMISSION_DISABLED",
  "INVOICE_MARKED_PAID",
  "INVOICE_MARKED_UNPAID",
  "AD_ACCOUNT_CREATED",
  "AD_ACCOUNT_UPDATED",
  "TOPUP_APPROVED",
  "TOPUP_REJECTED",
  "TOPUP_CREATED",
  "TOPUP_DELETED",
  "AD_ACCOUNT_REQUEST_APPROVED",
  "AD_ACCOUNT_REQUEST_REJECTED",
  "EXCHANGE_RATES_UPDATED",
] as const;

export const ACTIVITY_LOG_DB_ACTIONS = ["INSERT", "UPDATE", "DELETE"] as const;

export type ActivityLogAction = (typeof ACTIVITY_LOG_ACTIONS)[number];
export type ActivityLogDbAction = (typeof ACTIVITY_LOG_DB_ACTIONS)[number];
