export const DATE_FORMAT = "DD-MM-YYYY";
export const DATE_TIME_FORMAT = "DD-MM-YYYY HH:mm";

export const CURRENCY_SYMBOLS: Record<string, string> = {
  AED: "AED",
  AFN: "؋",
  ALL: "L",
  AMD: "֏",
  ANG: "ƒ",
  AOA: "Kz",
  ARS: "$",
  AUD: "A$",
  AWG: "ƒ",
  AZN: "₼",
  BAM: "KM",
  BBD: "Bds$",
  BDT: "৳",
  BGN: "лв",
  BHD: ".د.ب",
  BIF: "FBu",
  BMD: "BD$",
  BND: "B$",
  BOB: "Bs.",
  BRL: "R$",
  BSD: "B$",
  BTN: "Nu.",
  BWP: "P",
  BYN: "Br",
  BZD: "BZ$",
  CAD: "C$",
  CDF: "FC",
  CHF: "CHF",
  CLP: "$",
  CNY: "¥",
  COP: "$",
  CRC: "₡",
  CVE: "$",
  CZK: "Kč",
  DJF: "Fdj",
  DKK: "kr",
  DOP: "RD$",
  DZD: "دج",
  EGP: "£",
  ERN: "Nfk",
  ETB: "Br",
  EUR: "€",
  FJD: "FJ$",
  FKP: "£",
  GBP: "£",
  GEL: "₾",
  GHS: "₵",
  GIP: "£",
  GMD: "D",
  GNF: "FG",
  GTQ: "Q",
  GYD: "G$",
  HKD: "HK$",
  HNL: "L",
  HRK: "kn",
  HTG: "G",
  HUF: "Ft",
  IDR: "Rp",
  ILS: "₪",
  INR: "₹",
  IQD: "ع.د",
  IRR: "﷼",
  ISK: "kr",
  JEP: "£",
  JMD: "J$",
  JOD: "د.ا",
  JPY: "¥",
  KES: "KSh",
  KGS: "⃀",
  KHR: "៛",
  KMF: "CF",
  KRW: "₩",
  KWD: "د.ك",
  KYD: "CI$",
  KZT: "₸",
  LAK: "₭",
  LBP: "ل.ل",
  LKR: "Rs",
  LRD: "L$",
  LSL: "L",
  LYD: "ل.د",
  MAD: "د.م.",
  MDL: "L",
  MGA: "Ar",
  MKD: "ден",
  MMK: "K",
  MNT: "₮",
  MOP: "MOP$",
  MRU: "UM",
  MUR: "₨",
  SEK: "kr",
  UAH: "UAH",
  USD: "$",
};

export const TOPUP_TYPES = [
  { label: "Top-Up", value: "top-up" },
  { label: "First Top-Up", value: "first-top-up" },
  { label: "Extra Ad Account", value: "extra-ad-account" },
  { label: "Subscription", value: "subscription" },
];

export const PLATFORMS = [
  { label: "Meta-HK-Premium", value: "hk-meta-premium" },
  { label: "Meta-HK-Business", value: "hk-meta-business" },
  { label: "Meta-HK-Business-Green", value: "hk-meta-business-green" },
  { label: "Meta-EU-Premium", value: "eu-meta-premium" },
  { label: "Meta-EU-PSM", value: "eu-meta-psm" },
  { label: "Meta-EU-PSM-GH", value: "eu-meta-psm-gh" },
  { label: "Meta-EU-GDN", value: "eu-meta-gdn" },
  { label: "Google", value: "google" },
  { label: "Tiktok", value: "tiktok" },
];
export const COMMISSION_TYPE_LABELS: Record<string, string> = {
  monthly: "Monthly",
  pct: "Topup %",
  monthly_pct: "Monthly + Topup %",
  onetime_pct: "One Time + Topup %",
  onetime: "One Time",
  onetime_monthly: "One Time + Monthly",
};

export const CURRENCIES = [
  { label: "€ Euro", value: "EUR" },
  { label: "$ US Dollar", value: "USD" },
  // { label: "£ British Pound", value: "GBP" },
  // { label: "HK$ Hong Kong Dollar", value: "HKD" },
];

export const TIMEZONES = [
  {
    label: "(GMT-12:00) International Date Line West",
    value: "GMT-12:00 (Etc/GMT+12)",
  },
  {
    label: "(GMT-11:00) Midway Island, Samoa",
    value: "GMT-11:00 (Pacific/Midway)",
  },
  { label: "(GMT-10:00) Hawaii", value: "GMT-10:00 (Pacific/Honolulu)" },
  { label: "(GMT-09:00) Alaska", value: "GMT-09:00 (US/Alaska)" },
  {
    label: "(GMT-08:00) Pacific Time (US & Canada)",
    value: "GMT-08:00 (America/Los_Angeles)",
  },
  {
    label: "(GMT-07:00) Mountain Time (US & Canada)",
    value: "GMT-07:00 (America/Denver)",
  },
  { label: "(GMT-07:00) Arizona", value: "GMT-07:00 (US/Arizona)" },
  {
    label: "(GMT-06:00) Central Time (US & Canada)",
    value: "GMT-06:00 (America/Chicago)",
  },
  {
    label: "(GMT-05:00) Eastern Time (US & Canada)",
    value: "GMT-05:00 (America/New_York)",
  },
  { label: "(GMT-05:00) Indiana (East)", value: "GMT-05:00 (US/East-Indiana)" },
  {
    label: "(GMT-04:00) Atlantic Time (Canada)",
    value: "GMT-04:00 (America/Halifax)",
  },
  {
    label: "(GMT-04:00) Caracas, La Paz",
    value: "GMT-04:00 (America/Caracas)",
  },
  { label: "(GMT-03:00) Santiago", value: "GMT-03:00 (America/Santiago)" },
  {
    label: "(GMT-02:30) Newfoundland",
    value: "GMT-02:30 (Canada/Newfoundland)",
  },
  { label: "(GMT-03:00) Brasilia", value: "GMT-03:00 (America/Sao_Paulo)" },
  {
    label: "(GMT-02:00) Mid-Atlantic",
    value: "GMT-02:00 (Atlantic/South_Georgia)",
  },
  { label: "(GMT-01:00) Azores", value: "GMT-01:00 (Atlantic/Azores)" },
  {
    label: "(GMT+00:00) Greenwich Mean Time : Dublin, London",
    value: "GMT+00:00 (Europe/London)",
  },
  {
    label: "(GMT+01:00) Amsterdam, Berlin, Rome, ",
    value: "GMT+01:00 (Europe/Berlin)",
  },
  { label: "(GMT+01:00) Paris", value: "GMT+01:00 (Europe/Paris)" },
  {
    label: "(GMT+02:00) Athens, Bucharest, Istanbul",
    value: "GMT+02:00 (Europe/Istanbul)",
  },
  {
    label: "(GMT+03:00) Moscow, St. Petersburg",
    value: "GMT+03:00 (Europe/Moscow)",
  },
  { label: "(GMT+04:00) Abu Dhabi, Muscat", value: "GMT+04:00 (Asia/Dubai)" },
  {
    label: "(GMT+05:00) Islamabad, Karachi",
    value: "GMT+05:00 (Asia/Karachi)",
  },
  {
    label: "(GMT+05:30) Chennai, Kolkata",
    value: "GMT+05:30 (Asia/Kolkata)",
  },
  { label: "(GMT+05:45) Kathmandu", value: "GMT+05:45 (Asia/Kathmandu)" },
  {
    label: "(GMT+06:00) Almaty, Novosibirsk",
    value: "GMT+06:00 (Asia/Almaty)",
  },
  {
    label: "(GMT+07:00) Bangkok, Hanoi, Jakarta",
    value: "GMT+07:00 (Asia/Bangkok)",
  },
  {
    label: "(GMT+08:00) Beijing, Hong Kong",
    value: "GMT+08:00 (Asia/Hong_Kong)",
  },
  { label: "(GMT+08:00) Singapore", value: "GMT+08:00 (Asia/Singapore)" },
  {
    label: "(GMT+09:00) Tokyo, Osaka, Sapporo",
    value: "GMT+09:00 (Asia/Tokyo)",
  },
  { label: "(GMT+09:30) Adelaide", value: "GMT+09:30 (Australia/Adelaide)" },
  {
    label: "(GMT+10:00)  Melbourne, Sydney",
    value: "GMT+10:00 (Australia/Sydney)",
  },
  {
    label: "(GMT+11:00) Magadan, New Caledonia",
    value: "GMT+11:00 (Asia/Magadan)",
  },
  {
    label: "(GMT+12:00) Auckland, Wellington",
    value: "GMT+12:00 (Pacific/Auckland)",
  },
  { label: "(GMT+13:00) Nuku'alofa", value: "GMT+13:00 (Pacific/Tongatapu)" },
];
