// Generates the Supabase AUTH email templates from the house layout
// (lib/pure-email-layout.ts), so the sign-up confirmation, the password
// reset and the rest look like every other mail we send.
//
// Supabase keeps these templates in its dashboard, not in this repo, so
// they are written to supabase/email-templates/ and pasted by hand:
// Authentication -> Emails -> (template) -> Subject + Message body.
//
//   node --import ./tests/ts-resolve.mjs --experimental-strip-types scripts/email-templates.ts
//
// The {{ .ConfirmationURL }}-style placeholders are Supabase's own; it
// fills them in when it sends.

import { mkdirSync, writeFileSync } from "node:fs";
import { emailLayout, emailPanel, emailParagraph } from "../lib/pure-email-layout";

type Template = { file: string; name: string; subject: string; html: string };

const templates: Template[] = [
  {
    file: "confirm-signup.html",
    name: "Confirm signup",
    subject: "Confirm your email — Prime Scale Media",
    html: emailLayout({
      preheader: "One click and your Prime Scale Media account is ready.",
      title: "Confirm your email",
      bodyHtml:
        emailParagraph("Welcome to Prime Scale Media. Press the button to confirm <b>{{ .Email }}</b> and open your account.") +
        emailParagraph("After that you add your company details, and you can top up and run your ad accounts."),
      cta: { label: "Confirm my email", href: "{{ .ConfirmationURL }}" },
      footnoteHtml:
        "Did not sign up? Ignore this email — no account is created without this click.",
    }),
  },
  {
    file: "invite-user.html",
    name: "Invite user",
    subject: "You're invited to Prime Scale Media",
    html: emailLayout({
      preheader: "Accept the invitation to set up your Prime Scale Media account.",
      title: "You're invited to Prime Scale Media",
      bodyHtml: emailParagraph("Accept the invitation to set up your account for <b>{{ .Email }}</b>."),
      cta: { label: "Accept invitation", href: "{{ .ConfirmationURL }}" },
      footnoteHtml: "Did not expect this invitation? Ignore this email — nothing happens until you accept it.",
    }),
  },
  {
    file: "magic-link.html",
    name: "Magic link",
    subject: "Your sign-in link — Prime Scale Media",
    html: emailLayout({
      preheader: "Your one-time link to sign in to Prime Scale Media.",
      title: "Sign in to Prime Scale Media",
      bodyHtml: emailParagraph("Press the button to sign in as <b>{{ .Email }}</b>. The link works once."),
      cta: { label: "Sign in", href: "{{ .ConfirmationURL }}" },
      footnoteHtml: "Did not ask for this? Ignore this email — nobody can sign in without the link.",
    }),
  },
  {
    file: "change-email.html",
    name: "Change email address",
    subject: "Confirm your new email address — Prime Scale Media",
    html: emailLayout({
      preheader: "Confirm the new email address for your Prime Scale Media account.",
      title: "Confirm your new email address",
      bodyHtml:
        emailParagraph("You asked to change the email address of your account.") +
        emailPanel("From → to", "{{ .Email }} &rarr; {{ .NewEmail }}"),
      cta: { label: "Confirm new address", href: "{{ .ConfirmationURL }}" },
      footnoteHtml: "Did not ask for this? Ignore this email — your address stays as it is — and message us on WhatsApp.",
    }),
  },
  {
    file: "reset-password.html",
    name: "Reset password",
    subject: "Reset your password — Prime Scale Media",
    html: emailLayout({
      preheader: "Choose a new password for your Prime Scale Media account.",
      title: "Reset your password",
      bodyHtml: emailParagraph("Press the button to choose a new password for <b>{{ .Email }}</b>."),
      cta: { label: "Choose a new password", href: "{{ .ConfirmationURL }}" },
      footnoteHtml: "Did not ask for this? Ignore this email — your password stays the same.",
    }),
  },
  {
    file: "reauthentication.html",
    name: "Reauthentication",
    subject: "Your verification code — Prime Scale Media",
    html: emailLayout({
      preheader: "Your Prime Scale Media verification code.",
      title: "Your verification code",
      bodyHtml:
        emailParagraph("Enter this code in the app to confirm it is you:") +
        emailPanel(
          "Code",
          '<span style="font-size:26px;letter-spacing:.3em;font-weight:800;">{{ .Token }}</span>',
        ),
      footnoteHtml: "Did not ask for this? Ignore this email and message us on WhatsApp.",
    }),
  },
];

const dir = "supabase/email-templates";
mkdirSync(dir, { recursive: true });
for (const t of templates) {
  writeFileSync(`${dir}/${t.file}`, t.html + "\n", "utf8");
}

const readme = [
  "# Supabase auth emails — paste these",
  "",
  "Generated by `scripts/email-templates.ts` from `lib/pure-email-layout.ts`,",
  "the same layout the app's own mails use. Do not edit the HTML here; change",
  "the script and run it again:",
  "",
  "```",
  "node --import ./tests/ts-resolve.mjs --experimental-strip-types scripts/email-templates.ts",
  "```",
  "",
  "## In Supabase",
  "",
  "1. **Authentication → Emails (Templates)**: for each template below, paste",
  "   the subject, and the file's whole content into *Message body* (Source).",
  "2. **Authentication → Emails → SMTP settings**: set **Sender name** to",
  "   `Prime Scale Media` (it says `PSM Dashboard` today).",
  "",
  "| template in Supabase | subject | file |",
  "|---|---|---|",
  ...templates.map((t) => `| ${t.name} | ${t.subject} | \`${t.file}\` |`),
  "",
].join("\n");
writeFileSync(`${dir}/README.md`, readme, "utf8");

console.log(`wrote ${templates.length} templates to ${dir}`);
