-- =====================================================================
-- Only ever ONE unpaid subscription invoice
-- =====================================================================
-- ⚠️ APPLY ON SUPABASE MANUALLY.
--
-- THE BUG, in one line:
--
--     where subscription_id = p_subscription_id and status = 'unpaid'
--
-- That is how change_subscription_amount voids the invoice it is
-- superseding. It matches nothing when the invoice has no subscription_id
-- — and on this database there are such invoices. Confirmed by query:
--
--     invoice 0005-117  EUR 200  unpaid  subscription  subscription_id null
--                                                      period_start   null
--                                                      due_date       null
--     invoice 0005-118  EUR   5  unpaid  subscription  all three set
--
-- So lowering the plan from 200 to 5 did everything it was supposed to
-- except the one thing that mattered: the 200 stayed unpaid. The customer
-- then had two open subscription invoices, a billing card asking for the
-- superseded amount, and a Pay now button next to it.
--
-- TWO PARTS:
--   1. change_subscription_amount also voids unpaid type='subscription'
--      invoices that have NO subscription_id, for the same advertiser and
--      tenant. An advertiser may hold one active subscription, so such an
--      invoice is this subscription's or nobody's.
--   2. A one-off, generic void of the orphans that are already there —
--      only where a NEWER unpaid subscription invoice exists for the same
--      advertiser, so it can only ever void something that has already
--      been superseded. It never touches the newest one.
--
-- The UI no longer offers to pay anything but the newest unpaid monthly
-- invoice (e7e7062), so this is belt AND braces: the screen cannot ask,
-- and the row cannot be collected.
--
-- HOW THIS FILE WAS PRODUCED: generated by script from
-- 20260917200000_downgrade_refund_is_a_choice.sql — which is what is live
-- — with exactly one statement replaced. The body is otherwise byte-for-
-- byte identical, because it is 200 lines of money logic and
-- hand-transcribing it is how a clamp gets lost. The signature is
-- unchanged (uuid, numeric, text, boolean), so create-or-replace is
-- enough: no drop, and no moment where PostgREST sees two candidates.
--
-- ROLLBACK: re-apply 20260917200000. Voided invoices stay voided; put one
-- back with
--     update public.invoices set status = 'unpaid' where id = '<id>';
-- =====================================================================

set search_path = public;



create or replace function public.change_subscription_amount(
  p_subscription_id uuid,
  p_new_amount numeric,
  p_new_currency text default null,
  -- FALSE by default: a downgrade does NOT pay cash back unless the
  -- admin asks for it on this call. See the migration header.
  p_refund boolean default false
) returns jsonb
language plpgsql
security definer
set search_path = public
as $blk0$
declare
  v_uid      uuid := auth.uid();
  v_sub      public.subscriptions%rowtype;
  v_cur      text;
  v_company  uuid;
  v_advuser  uuid;
  v_curr     public.invoices%rowtype;
  v_delta    numeric;
  v_refund   numeric;
  v_adjpaid  numeric;
  v_collected numeric;
  v_refunded numeric;
  v_wallet   uuid;
  v_new_inv  uuid;
  v_period   date;
  v_action   text := 'updated';
begin
  if p_new_amount is null or p_new_amount < 0 then
    raise exception 'Invalid amount' using errcode = '22000';
  end if;

  select * into v_sub from public.subscriptions where id = p_subscription_id;
  if not found then
    raise exception 'Subscription not found' using errcode = '42704';
  end if;

  -- Admin of the sub's tenant (the super-admin is a tenant-owning admin,
  -- so role='admin' covers both). Service role (v_uid null) bypasses.
  if v_uid is not null and not exists (
    select 1 from public.user_profiles up
     where up.user_id = v_uid
       and up.tenant_id = v_sub.tenant_id
       and up.role = 'admin'
  ) then
    raise exception 'Forbidden' using errcode = '42501';
  end if;

  v_cur := upper(coalesce(nullif(p_new_currency, ''), v_sub.currency, 'EUR'));
  if v_cur not in ('USD', 'EUR') then
    raise exception 'Unsupported currency %', v_cur using errcode = '22000';
  end if;

  select user_id into v_advuser from public.advertisers where id = v_sub.advertiser_id;
  select id into v_company from public.companies where advertiser_id = v_sub.advertiser_id limit 1;

  -- Latest invoiced period for this subscription.
  select * into v_curr from public.invoices
   where subscription_id = p_subscription_id and period_start is not null
   order by period_start desc, created_at desc
   limit 1;

  if found and v_curr.status = 'paid'
     and upper(coalesce(v_curr.currency, 'EUR')) = v_cur then
    -- Reconcile the already-paid current period. Base the delta on the
    -- CURRENT effective amount (v_sub.amount, set by the previous change),
    -- not the original paid invoice total — otherwise repeated changes
    -- re-refund against the first price. Fall back to the invoice total
    -- for a first change where amount was never set.
    v_delta := p_new_amount - coalesce(v_sub.amount, v_curr.total, 0);

    if v_delta < 0 then
      -- ── Cheaper. This pays out REAL wallet cash, so bound it twice. ──

      -- (a) We are reversing an increase, so stop billing for it: void any
      --     adjustment for this period we never collected. That portion of
      --     the decrease is undone by voiding, not by a payout.
      --     NOTE: no updated_at on invoices.
      update public.invoices
         set status = 'void'
       where subscription_id = p_subscription_id
         and type = 'subscription_adjustment'
         and status = 'unpaid'
         and created_at >= v_curr.created_at;

      -- (b) Never pay out more than was actually COLLECTED for this period
      --     minus the new price. Adjustments carry no period_start, so they
      --     are scoped by having been raised at/after the current invoice.
      select coalesce(sum(total), 0) into v_adjpaid
        from public.invoices
       where subscription_id = p_subscription_id
         and type = 'subscription_adjustment'
         and status = 'paid'
         and created_at >= v_curr.created_at;

      -- (c) And subtract what we have ALREADY paid back for this period.
      --     Without this the baseline was rebuilt from scratch on every
      --     call and never moved, so an up-change that was never collected
      --     followed by a down-change re-refunded the same money — over and
      --     over, without bound. Scoped by a deterministic reference so an
      --     admin's unrelated manual wallet adjustments can never be
      --     mistaken for a refund of this period.
      select coalesce(sum(delta), 0) into v_refunded
        from public.wallet_adjustments
       where advertiser_id = v_sub.advertiser_id
         and status = 'approved'
         and reference = 'subscription_change_refund:' || v_curr.id::text;

      v_collected := coalesce(v_curr.total, 0) + coalesce(v_adjpaid, 0);
      v_refund := least(
        -v_delta,
        greatest(v_collected - p_new_amount - coalesce(v_refunded, 0), 0)
      );

      if p_refund and v_refund > 0 then
        if v_cur = 'USD' then
          update public.wallets
             set usd_balance = coalesce(usd_balance, 0) + v_refund, updated_at = now()
           where advertiser_id = v_sub.advertiser_id;
        else
          update public.wallets
             set eur_balance = coalesce(eur_balance, 0) + v_refund, updated_at = now()
           where advertiser_id = v_sub.advertiser_id;
        end if;

        -- Record the payout. This is what makes the clamp above hold across
        -- calls: the money used to leave with nothing written down except
        -- the new wallet balance, so the next call had no way to know it had
        -- already happened. status 'approved' because it is done, not
        -- proposed — wallet_adjustments carries no money-moving trigger
        -- (20260831190000 only touches updated_at and audits), so this
        -- records the payout without repeating it.
        select id into v_wallet from public.wallets
         where advertiser_id = v_sub.advertiser_id limit 1;
        if v_wallet is not null then
          insert into public.wallet_adjustments
            (tenant_id, advertiser_id, wallet_id, delta, currency, status,
             reference, reason, reviewed_at)
          values
            (v_sub.tenant_id, v_sub.advertiser_id, v_wallet, v_refund, v_cur,
             'approved',
             'subscription_change_refund:' || v_curr.id::text,
             'Subscription lowered to ' || p_new_amount::text || ' ' || v_cur,
             now());
        end if;

        v_action := 'refunded';
      elsif v_refund > 0 then
        -- There WAS a refundable difference and the admin chose not to pay
        -- it out. Nothing moves; the new price applies from here on.
        v_action := 'lowered_no_refund';
      else
        -- The decrease was fully absorbed by voiding an uncollected
        -- adjustment (or there was nothing to give back).
        v_action := 'adjustment_voided';
      end if;

    elsif v_delta > 0 and v_company is not null then
      -- pricier → invoice the difference (unpaid).
      insert into public.invoices
        (advertiser_id, tenant_id, company_id, subscription_id, type, currency,
         total, items, status, due_date)
      values
        (v_sub.advertiser_id, v_sub.tenant_id, v_company, p_subscription_id,
         'subscription_adjustment', v_cur, v_delta,
         jsonb_build_array(jsonb_build_object(
           'name', 'Subscription change adjustment', 'rate', v_delta,
           'amount', v_delta, 'quantity', 1, 'tax', 0, 'currency', v_cur)),
         'unpaid', now() + interval '7 days')
      returning id into v_new_inv;
      v_action := 'charged_difference';
    end if;
  else
    -- No paid current period → void unpaid subscription invoices (detach
    -- their period so the unique index frees up) and reissue one.
    -- NOTE: no updated_at on invoices. See 20260901440000 — writing it
    -- here is what made this RPC 400 on every real invoice.
    -- ALSO the ones with no subscription_id. This is the whole point of
    -- this migration: `where subscription_id = p_subscription_id` matches
    -- NOTHING for an invoice whose subscription_id is null, and live has
    -- exactly such invoices — raised at signup, type 'subscription', with
    -- no subscription_id, no period_start and no due_date. Lowering a plan
    -- from 200 to 5 therefore issued a new 5 invoice and left the 200
    -- standing as unpaid, so the customer's billing page showed two open
    -- subscription invoices and offered to pay the superseded one.
    --
    -- An orphan cannot belong to a DIFFERENT subscription: an advertiser is
    -- allowed one active subscription (createSubscriptionAsAdmin refuses a
    -- second), so an unpaid type='subscription' invoice for this advertiser
    -- with no link is this subscription's, or it is nobody's. Either way it
    -- must not stay collectable.
    --
    -- Scoped hard: unpaid only, type 'subscription' only (never an
    -- adjustment or a manual invoice), and the same advertiser AND tenant.
    update public.invoices
       set status = 'void', period_start = null
     where status = 'unpaid'
       and (
         subscription_id = p_subscription_id
         or (
           subscription_id is null
           and type = 'subscription'
           and advertiser_id = v_sub.advertiser_id
           and tenant_id = v_sub.tenant_id
         )
       );

    if v_company is not null then
      v_period := coalesce(v_sub.next_payment_date::date, current_date);
      insert into public.invoices
        (advertiser_id, tenant_id, company_id, subscription_id, type, currency,
         total, items, status, period_start, due_date)
      values
        (v_sub.advertiser_id, v_sub.tenant_id, v_company, p_subscription_id,
         'subscription', v_cur, p_new_amount,
         jsonb_build_array(jsonb_build_object(
           'name', 'Monthly subscription', 'rate', p_new_amount,
           'amount', p_new_amount, 'quantity', 1, 'tax', 0, 'currency', v_cur)),
         'unpaid', v_period, now() + interval '7 days')
      returning id into v_new_inv;
      v_action := 'reissued';
    end if;
  end if;

  update public.subscriptions
     set amount = p_new_amount, currency = v_cur, updated_at = now()
   where id = p_subscription_id;

  begin
    insert into public.notifications
      (recipient_user_id, tenant_id, type, payload, is_read)
    values
      (v_advuser, v_sub.tenant_id, 'subscription_changed',
       jsonb_build_object('amount', p_new_amount, 'currency', v_cur,
                          'action', v_action), false);
  exception when others then null; end;

  return jsonb_build_object('action', v_action, 'new_invoice', v_new_inv,
                            'amount', p_new_amount, 'currency', v_cur);
end;
$blk0$;
revoke all on function public.change_subscription_amount(uuid, numeric, text, boolean) from public, anon;
grant execute on function public.change_subscription_amount(uuid, numeric, text, boolean) to authenticated, service_role;

-- ── Part 2: the orphans already on the table ─────────────────────────
-- Generic, not keyed to invoice 117. An orphan is voided ONLY when the
-- same advertiser has a NEWER unpaid subscription invoice — that newer one
-- is what the plan actually costs now, and it is the one the billing page
-- shows. Without that condition this could void a lone unpaid invoice that
-- is genuinely owed.
update public.invoices o
   set status = 'void', period_start = null
 where o.status = 'unpaid'
   and o.type = 'subscription'
   and o.subscription_id is null
   and exists (
     select 1
       from public.invoices n
      where n.advertiser_id = o.advertiser_id
        and n.tenant_id = o.tenant_id
        and n.type = 'subscription'
        and n.status = 'unpaid'
        and n.id <> o.id
        and n.created_at > o.created_at
   );

-- ── Read it back ─────────────────────────────────────────────────────
-- unpaid_subscription_invoices_per_advertiser must be at most 1 for every
-- advertiser. If any row comes back with more than 1, STOP and say so:
-- the remaining duplicates are NOT orphans (they have a subscription_id),
-- which would mean something else is raising a second one.
select
  a.tenant_client_code,
  count(*) as unpaid_subscription_invoices
  from public.invoices i
  join public.advertisers a on a.id = i.advertiser_id
 where i.type = 'subscription'
   and i.status = 'unpaid'
 group by a.tenant_client_code
 having count(*) > 1;
