-- =====================================================================
-- The first top-up has no minimum — on the server too
-- =====================================================================
-- ⚠️ APPLY ON SUPABASE MANUALLY. This unblocks a real, already-sent
-- transfer: a 5 EUR payment was made and the claim for it cannot be
-- filed until this is applied.
--
-- WHAT HAPPENED, exactly:
--   1. The customer's screen computes the minimum with
--      lib/min-topup.ts → plan not paid yet, so NO minimum.
--   2. They fill in 5, get TURLIT's IBAN and the reference, and make the
--      transfer.
--   3. They upload the slip and press Submit Request.
--   4. wallet_topup_advertiser_create refuses: 'Amount below minimum',
--      because it read wallets.min_topup directly — and that column has
--      a DEFAULT of 300.
--
-- The money was already gone. A client-side rule the server does not
-- share is not a rule, it is a trap.
--
-- This migration makes the RPC obey the same rule as the screen, and
-- makes the error say the actual number instead of "below minimum".
--
-- Nothing else in the function changes: same signature, same reference
-- rotation, same insert. Generated by script from
-- 20260828120000_wallet_rpcs.sql with exactly two edits (three new
-- declarations and the minimum block), so the rest is byte-identical.
-- =====================================================================

set search_path = public;

create or replace function public.wallet_topup_advertiser_create(
  p_amount        numeric,
  p_currency      text,
  p_payment_slip  text default null
)
returns public.wallet_topups
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid       uuid := auth.uid();
  v_profile   record;
  v_adv       public.advertisers%rowtype;
  v_wallet    public.wallets%rowtype;
  v_new       public.wallet_topups%rowtype;
  v_new_ref   text;
  v_plan_active boolean;
  v_community text;
  v_min       numeric;
begin
  if v_uid is null then
    raise exception 'Unauthorized' using errcode = '28000';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'Amount must be positive' using errcode = '22000';
  end if;
  if p_currency is null or p_currency not in ('USD', 'EUR') then
    raise exception 'Invalid currency' using errcode = '22000';
  end if;

  select id, user_id, tenant_id, role
    into v_profile
    from public.user_profiles
   where user_id = v_uid
   order by created_at asc
   limit 1;
  if not found then
    raise exception 'Forbidden' using errcode = '42501';
  end if;

  select * into v_adv
    from public.advertisers
   where user_id = v_uid
     and tenant_id = v_profile.tenant_id
   limit 1;
  if not found then
    raise exception 'No advertiser profile' using errcode = '42501';
  end if;

  select * into v_wallet
    from public.wallets
   where advertiser_id = v_adv.id
     and tenant_id = v_profile.tenant_id
   limit 1;
  if not found then
    raise exception 'Wallet not found' using errcode = '42704';
  end if;

  -- ── The minimum, by the same rule the screen uses ──────────────────
  -- This used to be: if wallets.min_topup is not null and the amount is
  -- under it, refuse. wallets.min_topup has a COLUMN DEFAULT of 300, so
  -- that read "every advertiser must send at least 300 on their very first
  -- transfer" — while lib/min-topup.ts, which is what the customer's screen
  -- obeys, says there is NO minimum until the plan is actually paid for.
  --
  -- The two disagreed, and the customer lost: the dialog accepted 5,
  -- validated it against a floor of 0, took the bank details, took the
  -- payment slip, and then the RPC threw 'Amount below minimum' on submit.
  -- Somebody had already made the transfer by then.
  --
  -- Same rule, both sides:
  --   plan not paid yet  → no minimum. This payment is HOW the plan gets
  --                        paid; a floor on it is the wrong way round.
  --   plan running       → the stored value wins (0 included: that is an
  --                        admin's decision about this customer), else the
  --                        community floor, else 300.
  --
  -- "Plan running" is the server's version of the same three facts the
  -- screen checks: an active subscription, at least one PAID subscription
  -- invoice, and nothing unpaid outstanding.
  select
    exists (
      select 1 from public.subscriptions su
       where su.advertiser_id = v_adv.id
         and su.status = 'active'
    )
    and exists (
      select 1 from public.invoices i
       where i.advertiser_id = v_adv.id
         and i.type = 'subscription'
         and i.status = 'paid'
    )
    and not exists (
      select 1 from public.invoices i
       where i.advertiser_id = v_adv.id
         and i.type = 'subscription'
         and i.status not in ('paid', 'void')
    )
    into v_plan_active;

  if v_plan_active then
    if v_wallet.min_topup is not null then
      v_min := v_wallet.min_topup;
    else
      -- A community IS the advertiser's plan: a plans row with
      -- kind='community', reached through advertiser_plans. Mirrors
      -- hooks/use-advertiser-communities.ts and the COMMUNITY_MIN_TOPUP
      -- table in lib/min-topup.ts.
      select lower(p.name) into v_community
        from public.advertiser_plans ap
        join public.plans p
          on p.id = ap.plan_id
         and p.kind = 'community'
       where ap.advertiser_id = v_adv.id
       limit 1;
      v_min := case when v_community = 'nsa' then 250 else 300 end;
    end if;

    if p_amount < v_min then
      -- Say the number. "Amount below minimum" with no figure sends the
      -- customer back to a form to guess.
      raise exception 'Minimum top-up is % %', v_min, p_currency
        using errcode = '22000';
    end if;
  end if;

  insert into public.wallet_topups (
    wallet_id,
    advertiser_id,
    tenant_id,
    currency,
    amount,
    status,
    created_by,
    reference_no,
    payment_slip
  ) values (
    v_wallet.id,
    v_adv.id,
    v_wallet.tenant_id,
    p_currency,
    p_amount,
    'pending',
    v_profile.id,
    v_wallet.reference_no,
    p_payment_slip
  )
  returning * into v_new;

  -- Rotate the wallet's reference_no so the next topup gets a fresh code.
  v_new_ref := lpad((floor(random() * 1000000000)::bigint)::text, 10, '0');
  update public.wallets
     set reference_no = v_new_ref,
         updated_at = now()
   where id = v_wallet.id;

  return v_new;
end;
$$;

revoke all on function public.wallet_topup_advertiser_create(numeric, text, text) from public;
grant execute on function public.wallet_topup_advertiser_create(numeric, text, text) to authenticated;
